production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: anagram_development
  pool: 5
  host: localhost
  username: postgres
  password: greycat1
    
test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: postgres
  password: greycat1